---
abstract: 'A set of modules and scripts for parsing OWL ontologies'
author:
  - 'Tomasz Adamusiak <tomasz@cpan.org>'
build_requires:
  File::Temp: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: OWL-Simple
provides:
  OWL::Simple::Class:
    file: lib/OWL/Simple/Class.pm
    version: 0.05
  OWL::Simple::OBOWriter:
    file: lib/OWL/Simple/OBOWriter.pm
    version: 0.02
  OWL::Simple::Parser:
    file: lib/OWL/Simple/Parser.pm
    version: 0.07
recommends:
  Benchmark: 0
  GO::Parser: 0
  Getopt::Long: 0
  IO::File: 0
  IO::Handle: 0
  Text::LevenshteinXS: 0
requires:
  Log::Log4perl: 0
  Moose: 0.89
  XML::Parser: 2.34
resources:
  license: http://www.gnu.org/licenses/old-licenses/gpl-1.0.txt
version: 0.43
